### ISSUE TITLE
having error running this

### ISSUE THREAD

**Issue by SeasonPhan** [LukeAz/cloudflare-dynamic-dns-updater#1]
Traceback (most recent call last):
  File "cf-dns.py", line 36, in <module>
    if namedns['result'][0]['content'] != currentip:
KeyError: 'result'

please help me resolve the problem

**Comment by LukeAz** [comment]
Hi @SeaSon2002, sorry for the late reply.
Are you sure you have correctly created the required api token?
You can follow this instructions:

1) How to create a Cloudflare api token for this application
- Go in your profile in your dashboard
- Select “API Tokens”
- Create a new token api
- Select “Edit zone DNS” templates
- In “Permissions” select ZONE -> DNS -> READ
- In “Zone Resources” select INCLUDE -> your zone or all
- If you want you can define a TTL for your token
- Continue to summary
- Create Token
- Copy your token in the cf-dns.py file

2) How to get the zone id token
- Go in your dashboard and select the correct domain
- In the overview pannel you can found this token

3) How to get the record name
- Go in your DNS dashboard 
- If you have a subdomain you must enter subdomain.domain.it

If you need more help write to me, bye.
